Require ruby-3.3.0 for standalone pre-commit hook (#528)
markdownlint requires at >=ruby-3.0 to install, however some systems
still ship with older versions, e.g., macos-15.6.1 ships with a version
identifying as `ruby 2.6.10p210`. On such systems installing the
pre-commit hook usually fails, e.g.,

```console
$ pre-commit run -a
[INFO] Initializing environment for https://github.com/markdownlint/markdownlint.
[INFO] Installing environment for https://github.com/markdownlint/markdownlint.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby', '/usr/bin/gem', 'install', '--no-document', '--no-format-executable', '--no-use
r-install', '--install-dir', '/Users/user/.cache/pre-commit/repo1gih9_rf/rbenv-system/gems', '--bindir', '/Users/user/.cache/pre-commit/repo1gih9_rf/rbenv-system/gems/bin', 'mdl-0.12.0.gem')
return code: 1
stdout:
    Successfully installed concurrent-ruby-1.3.5
    Successfully installed chef-utils-18.8.11
stderr:
    Ignoring jaro_winkler-1.5.4 because its extensions are not built. Try: gem pristine jaro_winkler --version 1.5.4
    ERROR:  Error installing mdl-0.12.0.gem:
        mixlib-shellout requires Ruby version >= 3.0. The current ruby version is 2.6.10.210.
Check the log at /Users/user/.cache/pre-commit/pre-commit.log
```

The only way to fix this is for users to specify a global
`default_language_version` in `.pre-commit-config.yaml`. This however
applies to all hooks using ruby.

This patch instead hardcodes a reasonably recent version requirement in
this hook's config.

Closes #521.

Signed-off-by: Benjamin Bannier <bbannier@gmail.com>